volumes:
  amis-app-sync: { external: true }
  bundle:        { driver: local }
  config:        { driver: local }
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - amis-app-sync:/srv/web:nocopy
      - bundle:/bundle
      - config:/config
    networks:
      default:
        aliases:
          - amis
